print("Psalm 37:13 but the Lord laughs at the wicked, for he knows their day is coming.")
print("Luke 10:18 'I saw Satan fall like lightning from heaven.'")
print("1 Kings 19:27 Cry louder to your Gods if you want them to hear you, maybe they are just sleeping")
print("Proverbs 24:16 For though the righteous fall seven times, they rise again, but; the wicked stumble when calamity strikes.")
print("saiah 45:5 I am the Lord, and there is no other;apart from me there is no God.I will strengthen you, though you have not acknowledged me,")
print("Matthew 12:30–32 (NIV): 30 “Whoever is not with me is against me, and whoever does not gather with me scatters. 31 And so I tell you, every kind of sin and slander can be forgiven, but blasphemy against the Spirit will not be forgiven. 32 Anyone who speaks a word against the Son of Man will be forgiven, but anyone who speaks against the Holy Spirit will not be forgiven, either in this age or in the age to come.")
print("Proverbs 3:5-8 Trust in the Lord with all your heart and lean not on your own understanding;in all your ways submit to him,and he will make your paths straight. Do not be wise in your own eyes;fear the Lord and shun evil. This will bring health to your body and nourishment to your bones.")
print("Isaiah 41:10 Do not fear, for I am with you do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.")
print("Romans 12:19 Do not take revenge, my dear friends, but leave room for God’s wrath, for it is written: “It is mine to avenge; I will repay,”[a] says the Lord.")
print("John 8:58 “Very truly I tell you,” Jesus answered, “before Abraham was born, I am!”")
print("Revelation 1:8 “I am the Alpha and the Omega,” says the Lord God, “who is, and who was, and who is to come, the Almighty.”")
print("John 8:7 “So when they continued asking him, he lifted up himself, and said unto them, He that is without sin among you, let him first cast a stone at her.”")
print("Matthew 6:13 “And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, for ever. Amen.”")
print("Isaiah 40:31 “But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.”")
print("Joshua 1:9 “Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.”")
print("Matthew 10:34 “Think not that I am come to send peace on earth: I came not to send peace, but a sword.”")
input("Press Enter to exit...")